# Generated by Django 5.2 on 2025-05-04 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20)),
                ('status_novo', models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.ordemservico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
