# Generated by Django 5.2 on 2025-05-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historicostatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='recibo_entrega',
            field=models.FileField(blank=True, null=True, upload_to='recibos/'),
        ),
    ]
