# Generated by Django 5.2 on 2025-05-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_equipamento_cliente_alter_equipamento_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
            preserve_default=False,
        ),
    ]
