# Generated by Django 5.2 on 2025-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_celular_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], default='AGUARDANDO', max_length=20),
        ),
    ]
