# Generated by Django 5.2 on 2025-05-04 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ordemservico_ultima_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatus',
            options={'ordering': ['-data_alteracao'], 'verbose_name': 'Histórico de Status', 'verbose_name_plural': 'Históricos de Status'},
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.ordemservico', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_anterior',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_novo',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='historicostatus',
            index=models.Index(fields=['ordem', 'data_alteracao'], name='core_histor_ordem_i_b41486_idx'),
        ),
        migrations.AddIndex(
            model_name='historicostatus',
            index=models.Index(fields=['usuario', 'data_alteracao'], name='core_histor_usuario_497931_idx'),
        ),
    ]
