# Generated by Django 5.2 on 2025-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordemservico_recibo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
    ]
