# Generated by Django 5.2 on 2025-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_equipamento_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicostatus',
            name='status_anterior',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('AGUARDANDO APROVAÇÃO', 'Em andamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_novo',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('AGUARDANDO APROVAÇÃO', 'Em andamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], max_length=20, verbose_name='Novo Status'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando orçamento'), ('AGUARDANDO APROVAÇÃO', 'Em andamento'), ('APROVADO', 'Orçamento aprovado'), ('RECUSADO', 'Orçamento recusado'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Equipamento entregue')], default='AGUARDANDO', max_length=20),
        ),
    ]
