# Generated by Django 5.2 on 2025-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_historicostatus_status_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
